---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cloudflarebeat::default]
    data_bags_path: "test/integration/data_bags"
    attributes:
      cloudflarebeat:
